name: wedding_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  cached_network_image: ^3.2.1
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  flutter_screenutil: ^5.5.3+2
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  shimmer: ^2.0.0
  get_storage: ^2.0.3
  mask_text_input_formatter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.5

flutter_native_splash:

  android: true
  ios: true 

  color: "#FFFFFF"
  image: assets/images/app_icon.png


  
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

 
  fonts:
    - family: georgia
      fonts:
        - asset: assets/fonts/Georgia.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
